"""Tests for pattern matching."""

import re

import pytest

from ai_trace_scan.patterns import (
    BOT_AUTHOR_PATTERNS,
    BRANCH_PATTERNS,
    COMMENT_PATTERNS,
    COMMIT_MSG_PATTERNS,
    DIFF_PATTERNS,
    PROSE_PATTERNS,
    TRAILER_PATTERNS,
    WORKFLOW_PATTERNS,
)


class TestTrailerPatterns:
    @pytest.mark.parametrize(
        "line,expected_label",
        [
            (
                "Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>",
                "Co-authored-by Copilot trailer",
            ),
            (
                "Co-authored-by: GitHub Copilot <copilot@github.com>",
                "Co-authored-by Copilot trailer",
            ),
            ("Co-authored-by: Claude <claude@anthropic.com>", "Co-authored-by Claude trailer"),
            (
                "Co-authored-by: Anthropic Assistant <a@anthropic.com>",
                "Co-authored-by Claude trailer",
            ),
            ("Co-authored-by: ChatGPT <chatgpt@openai.com>", "Co-authored-by GPT/OpenAI trailer"),
            ("Co-authored-by: GPT-4 <gpt4@openai.com>", "Co-authored-by GPT/OpenAI trailer"),
            ("Co-authored-by: Cursor <cursor@cursor.sh>", "Co-authored-by AI tool trailer"),
            ("Co-authored-by: Gemini <gemini@google.com>", "Co-authored-by AI tool trailer"),
            ("Co-authored-by: Windsurf <windsurf@codeium.com>", "Co-authored-by AI tool trailer"),
            ("Co-authored-by: Cody <cody@sourcegraph.com>", "Co-authored-by AI tool trailer"),
            ("Co-authored-by: Amazon Q <q@amazon.com>", "Co-authored-by AI tool trailer"),
            ("Co-authored-by: Bolt <bolt@stackblitz.com>", "Co-authored-by AI tool trailer"),
            ("Co-authored-by: Lovable <lovable@lovable.dev>", "Co-authored-by AI tool trailer"),
            ("Signed-off-by: dependabot[bot] <support@github.com>", "Bot Signed-off-by trailer"),
            ("Generated-by: copilot", "Generated-by AI trailer"),
        ],
    )
    def test_matches_known_trailers(self, line, expected_label):
        matched = False
        for pattern, label in TRAILER_PATTERNS:
            if pattern.search(line):
                assert label == expected_label
                matched = True
                break
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "Co-authored-by: John Doe <john@example.com>",
            "Co-authored-by: Jane Smith <jane@corp.com>",
            "Signed-off-by: Developer <dev@example.com>",
        ],
    )
    def test_ignores_human_trailers(self, line):
        for pattern, _ in TRAILER_PATTERNS:
            assert not pattern.search(line), f"False positive on: {line}"


class TestCommitMsgPatterns:
    @pytest.mark.parametrize(
        "msg",
        [
            "as an AI, I cannot",
            "as a language model",
            "per your instructions",
            "review: Copilot",
            "generated by Copilot",
            "generated with Claude",
            "generated using AI",
            "copilot suggested this fix",
            "claude wrote this function",
            "windsurf suggested this approach",
            "cody generated the boilerplate",
            "amazon q wrote this test",
        ],
    )
    def test_matches_agentic_language(self, msg):
        matched = any(p.search(msg) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"

    def test_emoji_prefix_detection(self):
        emoji_patterns = [(p, label) for p, label in COMMIT_MSG_PATTERNS if "Emoji" in label]
        assert len(emoji_patterns) == 1, "Expected exactly one emoji pattern"
        pattern, _label = emoji_patterns[0]
        assert pattern.search("\U0001f680 Add feature")
        assert pattern.search("\U0001f41b Fix bug")
        assert pattern.search("\u2728 Polish code")
        assert not pattern.search("Add feature")
        assert not pattern.search("fix: something")

    @pytest.mark.parametrize(
        "msg",
        [
            "Fix null pointer in user service",
            "Refactor authentication module",
            "Update dependencies to latest",
        ],
    )
    def test_ignores_normal_messages(self, msg):
        # Exclude emoji pattern — it's positional, not word-based
        non_emoji = [(p, label) for p, label in COMMIT_MSG_PATTERNS if "Emoji" not in label]
        for pattern, _ in non_emoji:
            assert not pattern.search(msg), f"False positive on: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "as you requested, updated the config",
            "you asked for this refactor",
            "you asked me to fix the tests",
            "per your request, added validation",
            "as you mentioned, the API needs auth",
            "as you suggested, split the module",
            "based on your feedback, simplified the logic",
            "based on your instructions, rewrote the parser",
            "let me know if you'd like any changes",
            "let me know if you would like me to adjust",
        ],
    )
    def test_matches_ai_to_user_language(self, msg):
        matched = any(p.search(msg) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "I've implemented the new auth flow",
            "I've added unit tests for the parser",
            "I've refactored the database layer",
            "I've updated the README",
            "I have created a new module for caching",
            "I have fixed the race condition",
            "here's the implementation for the feature",
            "here is the updated config",
            "I'll create the migration script",
            "I'll update the docs after merging",
        ],
    )
    def test_matches_ai_first_person_voice(self, msg):
        matched = any(p.search(msg) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "Updated the config per review comments",
            "Requested changes from PR review",
            "Fix based on CI feedback",
        ],
    )
    def test_ignores_normal_messages_with_similar_words(self, msg):
        non_emoji = [(p, label) for p, label in COMMIT_MSG_PATTERNS if "Emoji" not in label]
        for pattern, _ in non_emoji:
            assert not pattern.search(msg), f"False positive on: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "```python\nprint('hello')\n```",
            "## Changes\n- Added auth module",
            "# Summary\nUpdated the API",
            "Changes made:\n",
            "Summary of changes:\n",
            "Absolutely! Here's the updated code",
        ],
    )
    def test_matches_markdown_and_structured_commits(self, msg):
        matched = any(p.search(msg) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "Used claude-3.5-sonnet for this",
            "Tested with gpt-4o",
            "Generated by gemini-pro",
            "Based on o1-preview output",
        ],
    )
    def test_matches_model_version_references(self, msg):
        matched = any(p.search(msg) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "feel free to ask if anything is unclear",
            "don't hesitate to reach out",
            "I'd recommend using a factory pattern",
            "I'd suggest adding validation here",
            "great question! Here's how it works",
            "good catch! Fixed the edge case",
        ],
    )
    def test_matches_conversational_filler(self, msg):
        matched = any(p.search(msg) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"


class TestDiffPatterns:
    @pytest.mark.parametrize(
        "line",
        [
            "# as you requested, updated the handler",
            "// per your request, added error handling",
            "# per your instructions, refactored this",
            "// let me know if you'd like changes",
            "# I've implemented this based on the spec",
            "// I've added the validation here",
            "# I have created a helper for this",
            "# this code was generated by copilot",
            "// TODO: copilot suggested this approach",
            "# TODO ai: review this implementation",
        ],
    )
    def test_matches_conversational_patterns_in_code(self, line):
        matched = any(p.search(line) for p, _ in DIFF_PATTERNS)
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "# Handle user authentication",
            "// Parse the request body",
            "# TODO: refactor this later",
            "// Fix the edge case for empty arrays",
        ],
    )
    def test_ignores_normal_code_comments(self, line):
        for pattern, _ in DIFF_PATTERNS:
            assert not pattern.search(line), f"False positive on: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "# this code was generated by windsurf",
            "// TODO cody: check this",
            "# TODO amazon q: needs review",
            "// this function was written using bolt",
            "# this module was created with lovable",
        ],
    )
    def test_matches_new_tool_names(self, line):
        matched = any(p.search(line) for p, _ in DIFF_PATTERNS)
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            'model = "gpt-4o"',
            "# using claude-3.5-sonnet",
            "GEMINI_MODEL = 'gemini-1.5-flash'",
            "# tested with o1-preview",
        ],
    )
    def test_matches_model_version_in_code(self, line):
        matched = any(p.search(line) for p, _ in DIFF_PATTERNS)
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "# See https://chat.openai.com/share/abc123",
            "// Reference: https://claude.ai/chat/xyz789",
            "# From https://chatgpt.com/share/abc",
        ],
    )
    def test_matches_chat_share_urls(self, line):
        matched = any(p.search(line) for p, _ in DIFF_PATTERNS)
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "<!-- generated by copilot -->",
            "<!-- created with claude -->",
            "<!-- written using ai -->",
        ],
    )
    def test_matches_html_ai_comments(self, line):
        matched = any(p.search(line) for p, _ in DIFF_PATTERNS)
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "@ai-generated",
            " @generated",
            " @copilot",
        ],
    )
    def test_matches_ai_annotations(self, line):
        matched = any(p.search(line) for p, _ in DIFF_PATTERNS)
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "# implement your code here",
            "// add the actual logic here",
            "# write your implementation here",
            "// put the actual code here",
        ],
    )
    def test_matches_placeholder_code(self, line):
        matched = any(p.search(line) for p, _ in DIFF_PATTERNS)
        assert matched, f"No pattern matched: {line}"


class TestBotAuthorPatterns:
    @pytest.mark.parametrize(
        "email",
        [
            "copilot[bot]@users.noreply.github.com",
            "devin[bot]@users.noreply.github.com",
            "sweep[bot]@users.noreply.github.com",
            "223556219+Copilot@users.noreply.github.com",
            "amazon-q[bot]@users.noreply.github.com",
            "cody[bot]@users.noreply.github.com",
            "windsurf[bot]@users.noreply.github.com",
            "bolt[bot]@users.noreply.github.com",
            "lovable[bot]@users.noreply.github.com",
            "replit[bot]@users.noreply.github.com",
            "coderabbit[bot]@users.noreply.github.com",
            "sourcery[bot]@users.noreply.github.com",
            "pr-agent[bot]@users.noreply.github.com",
        ],
    )
    def test_matches_bot_emails(self, email):
        matched = any(p.search(email) for p, _ in BOT_AUTHOR_PATTERNS)
        assert matched, f"No pattern matched: {email}"

    @pytest.mark.parametrize(
        "email",
        [
            "developer@example.com",
            "john.doe@company.com",
            "dependabot[bot]@users.noreply.github.com",
        ],
    )
    def test_ignores_human_and_other_bot_emails(self, email):
        for pattern, _ in BOT_AUTHOR_PATTERNS:
            assert not pattern.search(email), f"False positive on: {email}"


class TestBranchPatterns:
    @pytest.mark.parametrize(
        "branch",
        [
            "copilot/fix-something",
            "copilot-workspace/feature",
            "claude/refactor",
            "ai-generated-fix",
            "ai/feature",
            "cursor-fix",
            "aider-refactor",
            "gemini-feature",
            "devin-implement",
            "sweep-cleanup",
            "windsurf-fix",
            "windsurf/refactor",
            "cody-suggest",
            "cody/fix",
            "amazonq-review",
            "bolt-scaffold",
            "lovable-generate",
            "replit-create",
            "v0-component",
        ],
    )
    def test_matches_ai_branch_names(self, branch):
        matched = any(re.search(p, branch, re.IGNORECASE) for p in BRANCH_PATTERNS)
        assert matched, f"No pattern matched: {branch}"

    @pytest.mark.parametrize(
        "branch",
        [
            "feature/user-auth",
            "fix/login-bug",
            "main",
            "release-2.14",
            "hotfix/critical-patch",
        ],
    )
    def test_ignores_normal_branch_names(self, branch):
        for pattern in BRANCH_PATTERNS:
            assert not re.search(pattern, branch, re.IGNORECASE), f"False positive on: {branch}"


class TestCommentPatterns:
    @pytest.mark.parametrize(
        "comment",
        [
            "# generated by copilot",
            "// generated with Claude",
            "/* generated using AI */",
            "# copilot-generated",
            "# copilot generated",
            "// claude wrote this",
            "# gpt4 generated this",
            "# @generated by copilot",
            "// generated by windsurf",
            "# generated with cody",
            "// gemini wrote this code",
        ],
    )
    def test_matches_ai_comments(self, comment):
        matched = any(p.search(comment) for p, _ in COMMENT_PATTERNS)
        assert matched, f"No pattern matched: {comment}"

    @pytest.mark.parametrize(
        "comment",
        [
            "# Auto-generated by protobuf compiler",
            "// This function handles authentication",
            "# TODO: refactor this later",
            "/* Copyright 2024 */",
        ],
    )
    def test_ignores_normal_comments(self, comment):
        for pattern, _ in COMMENT_PATTERNS:
            assert not pattern.search(comment), f"False positive on: {comment}"

    @pytest.mark.parametrize(
        "comment",
        [
            "# as you requested, refactored the module",
            "// per your request, added null checks",
            "# let me know if you'd like adjustments",
            "// I've implemented the caching layer",
            "# I've added the error boundary",
            "// I have created a wrapper for this",
        ],
    )
    def test_matches_conversational_comments(self, comment):
        matched = any(p.search(comment) for p, _ in COMMENT_PATTERNS)
        assert matched, f"No pattern matched: {comment}"

    @pytest.mark.parametrize(
        "comment",
        [
            "# uses claude-3.5-sonnet",
            "// model: gpt-4o",
            "# tested with gemini-1.5-flash",
        ],
    )
    def test_matches_model_versions_in_comments(self, comment):
        matched = any(p.search(comment) for p, _ in COMMENT_PATTERNS)
        assert matched, f"No pattern matched: {comment}"


class TestProsePatterns:
    @pytest.mark.parametrize(
        "text",
        [
            "Written by AI",
            "Authored with Copilot",
            "Created using Claude",
            "This document was generated by GPT",
            "This guide was written using Gemini",
            "Powered by Claude",
            "Built with Copilot",
            "Assisted by Windsurf",
            "Generated by Cody",
            "Authored with Amazon Q",
            "See https://chat.openai.com/share/abc123",
            "Reference: https://claude.ai/chat/xyz789",
            "Based on gpt-4o output",
            "Used claude-3.5-sonnet for generation",
        ],
    )
    def test_matches_ai_prose(self, text):
        matched = any(p.search(text) for p, _ in PROSE_PATTERNS)
        assert matched, f"No pattern matched: {text}"

    @pytest.mark.parametrize(
        "text",
        [
            "Written by the engineering team",
            "This document describes the API",
            "Built with React and TypeScript",
        ],
    )
    def test_ignores_normal_prose(self, text):
        for pattern, _ in PROSE_PATTERNS:
            assert not pattern.search(text), f"False positive on: {text}"


class TestWorkflowPatterns:
    @pytest.mark.parametrize(
        "line",
        [
            "uses: github/copilot-action@v1",
            "uses: anthropic/claude-action@main",
            "OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}",
            "ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_KEY }}",
            "GEMINI_API_KEY: ${{ secrets.GEMINI_KEY }}",
            "GOOGLE_AI_API_KEY: ${{ secrets.AI_KEY }}",
            "pip install anthropic",
            "pip install aider-chat",
            "uses: coderabbit/action@v1",
            "uses: sourcery/action@v1",
            "copilot-setup-steps",
            "uses: windsurf/action@v1",
            "uses: cody/review-action@v1",
        ],
    )
    def test_matches_ai_workflow_patterns(self, line):
        matched = any(p.search(line) for p, _ in WORKFLOW_PATTERNS)
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "uses: actions/checkout@v4",
            "uses: actions/setup-node@v3",
            "NODE_ENV: production",
            "pip install pytest",
        ],
    )
    def test_ignores_normal_workflow_lines(self, line):
        for pattern, _ in WORKFLOW_PATTERNS:
            assert not pattern.search(line), f"False positive on: {line}"
