"""Tests for pattern matching."""

import re

import pytest

from ai_trace_scan.patterns import (
    BOT_AUTHOR_PATTERNS,
    BRANCH_PATTERNS,
    COMMENT_PATTERNS,
    COMMIT_MSG_PATTERNS,
    DIFF_PATTERNS,
    TRAILER_PATTERNS,
)


class TestTrailerPatterns:
    @pytest.mark.parametrize(
        "line,expected_label",
        [
            (
                "Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>",
                "Co-authored-by Copilot trailer",
            ),
            (
                "Co-authored-by: GitHub Copilot <copilot@github.com>",
                "Co-authored-by Copilot trailer",
            ),
            ("Co-authored-by: Claude <claude@anthropic.com>", "Co-authored-by Claude trailer"),
            (
                "Co-authored-by: Anthropic Assistant <a@anthropic.com>",
                "Co-authored-by Claude trailer",
            ),
            ("Co-authored-by: ChatGPT <chatgpt@openai.com>", "Co-authored-by GPT/OpenAI trailer"),
            ("Co-authored-by: GPT-4 <gpt4@openai.com>", "Co-authored-by GPT/OpenAI trailer"),
            ("Co-authored-by: Cursor <cursor@cursor.sh>", "Co-authored-by AI tool trailer"),
            ("Co-authored-by: Gemini <gemini@google.com>", "Co-authored-by AI tool trailer"),
        ],
    )
    def test_matches_known_trailers(self, line, expected_label):
        matched = False
        for pattern, label in TRAILER_PATTERNS:
            if re.search(pattern, line, re.IGNORECASE):
                assert label == expected_label
                matched = True
                break
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "Co-authored-by: John Doe <john@example.com>",
            "Co-authored-by: Jane Smith <jane@corp.com>",
            "Signed-off-by: Developer <dev@example.com>",
        ],
    )
    def test_ignores_human_trailers(self, line):
        for pattern, _ in TRAILER_PATTERNS:
            assert not re.search(pattern, line, re.IGNORECASE), f"False positive on: {line}"


class TestCommitMsgPatterns:
    @pytest.mark.parametrize(
        "msg",
        [
            "as an AI, I cannot",
            "as a language model",
            "per your instructions",
            "review: Copilot",
            "generated by Copilot",
            "generated with Claude",
            "generated using AI",
            "copilot suggested this fix",
            "claude wrote this function",
        ],
    )
    def test_matches_agentic_language(self, msg):
        matched = any(re.search(p, msg, re.IGNORECASE) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"

    def test_emoji_prefix_detection(self):
        emoji_patterns = [(p, label) for p, label in COMMIT_MSG_PATTERNS if "Emoji" in label]
        assert len(emoji_patterns) == 1, "Expected exactly one emoji pattern"
        pattern, _label = emoji_patterns[0]
        assert re.search(pattern, "\U0001f680 Add feature")
        assert re.search(pattern, "\U0001f41b Fix bug")
        assert re.search(pattern, "\u2728 Polish code")
        assert not re.search(pattern, "Add feature")
        assert not re.search(pattern, "fix: something")

    @pytest.mark.parametrize(
        "msg",
        [
            "Fix null pointer in user service",
            "Refactor authentication module",
            "Update dependencies to latest",
        ],
    )
    def test_ignores_normal_messages(self, msg):
        # Exclude emoji pattern — it's positional, not word-based
        non_emoji = [(p, label) for p, label in COMMIT_MSG_PATTERNS if "Emoji" not in label]
        for pattern, _ in non_emoji:
            assert not re.search(pattern, msg, re.IGNORECASE), f"False positive on: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "as you requested, updated the config",
            "you asked for this refactor",
            "you asked me to fix the tests",
            "per your request, added validation",
            "as you mentioned, the API needs auth",
            "as you suggested, split the module",
            "based on your feedback, simplified the logic",
            "based on your instructions, rewrote the parser",
            "let me know if you'd like any changes",
            "let me know if you would like me to adjust",
        ],
    )
    def test_matches_ai_to_user_language(self, msg):
        matched = any(re.search(p, msg, re.IGNORECASE) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "I've implemented the new auth flow",
            "I've added unit tests for the parser",
            "I've refactored the database layer",
            "I've updated the README",
            "I have created a new module for caching",
            "I have fixed the race condition",
            "here's the implementation for the feature",
            "here is the updated config",
            "I'll create the migration script",
            "I'll update the docs after merging",
        ],
    )
    def test_matches_ai_first_person_voice(self, msg):
        matched = any(re.search(p, msg, re.IGNORECASE) for p, _ in COMMIT_MSG_PATTERNS)
        assert matched, f"No pattern matched: {msg}"

    @pytest.mark.parametrize(
        "msg",
        [
            "Updated the config per review comments",
            "Requested changes from PR review",
            "Fix based on CI feedback",
        ],
    )
    def test_ignores_normal_messages_with_similar_words(self, msg):
        non_emoji = [(p, label) for p, label in COMMIT_MSG_PATTERNS if "Emoji" not in label]
        for pattern, _ in non_emoji:
            assert not re.search(pattern, msg, re.IGNORECASE), f"False positive on: {msg}"


class TestDiffPatterns:
    @pytest.mark.parametrize(
        "line",
        [
            "# as you requested, updated the handler",
            "// per your request, added error handling",
            "# per your instructions, refactored this",
            "// let me know if you'd like changes",
            "# I've implemented this based on the spec",
            "// I've added the validation here",
            "# I have created a helper for this",
            "# this code was generated by copilot",
            "// TODO: copilot suggested this approach",
            "# TODO ai: review this implementation",
        ],
    )
    def test_matches_conversational_patterns_in_code(self, line):
        matched = any(re.search(p, line, re.IGNORECASE) for p, _ in DIFF_PATTERNS)
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize(
        "line",
        [
            "# Handle user authentication",
            "// Parse the request body",
            "# TODO: refactor this later",
            "// Fix the edge case for empty arrays",
        ],
    )
    def test_ignores_normal_code_comments(self, line):
        for pattern, _ in DIFF_PATTERNS:
            assert not re.search(pattern, line, re.IGNORECASE), f"False positive on: {line}"


class TestBotAuthorPatterns:
    @pytest.mark.parametrize(
        "email",
        [
            "copilot[bot]@users.noreply.github.com",
            "devin[bot]@users.noreply.github.com",
            "sweep[bot]@users.noreply.github.com",
            "223556219+Copilot@users.noreply.github.com",
        ],
    )
    def test_matches_bot_emails(self, email):
        matched = any(re.search(p, email, re.IGNORECASE) for p, _ in BOT_AUTHOR_PATTERNS)
        assert matched, f"No pattern matched: {email}"

    @pytest.mark.parametrize(
        "email",
        [
            "developer@example.com",
            "john.doe@company.com",
            "dependabot[bot]@users.noreply.github.com",
        ],
    )
    def test_ignores_human_and_other_bot_emails(self, email):
        for pattern, _ in BOT_AUTHOR_PATTERNS:
            assert not re.search(pattern, email, re.IGNORECASE), f"False positive on: {email}"


class TestBranchPatterns:
    @pytest.mark.parametrize(
        "branch",
        [
            "copilot/fix-something",
            "claude/refactor",
            "ai-generated-fix",
            "ai/feature",
            "cursor-fix",
            "aider-refactor",
            "gemini-feature",
            "devin-implement",
            "sweep-cleanup",
        ],
    )
    def test_matches_ai_branch_names(self, branch):
        matched = any(re.search(p, branch, re.IGNORECASE) for p in BRANCH_PATTERNS)
        assert matched, f"No pattern matched: {branch}"

    @pytest.mark.parametrize(
        "branch",
        [
            "feature/user-auth",
            "fix/login-bug",
            "main",
            "release-2.14",
            "hotfix/critical-patch",
        ],
    )
    def test_ignores_normal_branch_names(self, branch):
        for pattern in BRANCH_PATTERNS:
            assert not re.search(pattern, branch, re.IGNORECASE), f"False positive on: {branch}"


class TestCommentPatterns:
    @pytest.mark.parametrize(
        "comment",
        [
            "# generated by copilot",
            "// generated with Claude",
            "/* generated using AI */",
            "# copilot-generated",
            "# copilot generated",
            "// claude wrote this",
            "# gpt4 generated this",
            "# @generated by copilot",
        ],
    )
    def test_matches_ai_comments(self, comment):
        matched = any(re.search(p, comment, re.IGNORECASE) for p, _ in COMMENT_PATTERNS)
        assert matched, f"No pattern matched: {comment}"

    @pytest.mark.parametrize(
        "comment",
        [
            "# Auto-generated by protobuf compiler",
            "// This function handles authentication",
            "# TODO: refactor this later",
            "/* Copyright 2024 */",
        ],
    )
    def test_ignores_normal_comments(self, comment):
        for pattern, _ in COMMENT_PATTERNS:
            assert not re.search(pattern, comment, re.IGNORECASE), f"False positive on: {comment}"

    @pytest.mark.parametrize(
        "comment",
        [
            "# as you requested, refactored the module",
            "// per your request, added null checks",
            "# let me know if you'd like adjustments",
            "// I've implemented the caching layer",
            "# I've added the error boundary",
            "// I have created a wrapper for this",
        ],
    )
    def test_matches_conversational_comments(self, comment):
        matched = any(re.search(p, comment, re.IGNORECASE) for p, _ in COMMENT_PATTERNS)
        assert matched, f"No pattern matched: {comment}"
