"""Tests for pattern matching."""

import re
import pytest

from ai_trace_scan.patterns import (
    BOT_AUTHOR_PATTERNS,
    BRANCH_PATTERNS,
    COMMENT_PATTERNS,
    COMMIT_MSG_PATTERNS,
    TRAILER_PATTERNS,
)


class TestTrailerPatterns:
    @pytest.mark.parametrize("line,expected_label", [
        ("Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>",
         "Co-authored-by Copilot trailer"),
        ("Co-authored-by: GitHub Copilot <copilot@github.com>",
         "Co-authored-by Copilot trailer"),
        ("Co-authored-by: Claude <claude@anthropic.com>",
         "Co-authored-by Claude trailer"),
        ("Co-authored-by: Anthropic Assistant <a@anthropic.com>",
         "Co-authored-by Claude trailer"),
        ("Co-authored-by: ChatGPT <chatgpt@openai.com>",
         "Co-authored-by GPT/OpenAI trailer"),
        ("Co-authored-by: GPT-4 <gpt4@openai.com>",
         "Co-authored-by GPT/OpenAI trailer"),
        ("Co-authored-by: Cursor <cursor@cursor.sh>",
         "Co-authored-by AI tool trailer"),
        ("Co-authored-by: Gemini <gemini@google.com>",
         "Co-authored-by AI tool trailer"),
    ])
    def test_matches_known_trailers(self, line, expected_label):
        matched = False
        for pattern, label in TRAILER_PATTERNS:
            if re.search(pattern, line, re.IGNORECASE):
                assert label == expected_label
                matched = True
                break
        assert matched, f"No pattern matched: {line}"

    @pytest.mark.parametrize("line", [
        "Co-authored-by: John Doe <john@example.com>",
        "Co-authored-by: Jane Smith <jane@corp.com>",
        "Signed-off-by: Developer <dev@example.com>",
    ])
    def test_ignores_human_trailers(self, line):
        for pattern, _ in TRAILER_PATTERNS:
            assert not re.search(pattern, line, re.IGNORECASE), \
                f"False positive on: {line}"


class TestCommitMsgPatterns:
    @pytest.mark.parametrize("msg", [
        "as an AI, I cannot",
        "as a language model",
        "per your instructions",
        "review: Copilot",
        "generated by Copilot",
        "generated with Claude",
        "generated using AI",
        "copilot suggested this fix",
        "claude wrote this function",
    ])
    def test_matches_agentic_language(self, msg):
        matched = any(
            re.search(p, msg, re.IGNORECASE)
            for p, _ in COMMIT_MSG_PATTERNS
        )
        assert matched, f"No pattern matched: {msg}"

    def test_emoji_prefix_detection(self):
        pattern, label = COMMIT_MSG_PATTERNS[-1]
        assert re.search(pattern, "\U0001f680 Add feature")
        assert re.search(pattern, "\U0001f41b Fix bug")
        assert re.search(pattern, "\u2728 Polish code")
        assert not re.search(pattern, "Add feature")
        assert not re.search(pattern, "fix: something")

    @pytest.mark.parametrize("msg", [
        "Fix null pointer in user service",
        "Refactor authentication module",
        "Update dependencies to latest",
    ])
    def test_ignores_normal_messages(self, msg):
        # Exclude emoji pattern (last one) — it's positional, not word-based
        for pattern, _ in COMMIT_MSG_PATTERNS[:-1]:
            assert not re.search(pattern, msg, re.IGNORECASE), \
                f"False positive on: {msg}"


class TestBotAuthorPatterns:
    @pytest.mark.parametrize("email", [
        "copilot[bot]@users.noreply.github.com",
        "devin[bot]@users.noreply.github.com",
        "sweep[bot]@users.noreply.github.com",
        "223556219+Copilot@users.noreply.github.com",
    ])
    def test_matches_bot_emails(self, email):
        matched = any(
            re.search(p, email, re.IGNORECASE)
            for p, _ in BOT_AUTHOR_PATTERNS
        )
        assert matched, f"No pattern matched: {email}"

    @pytest.mark.parametrize("email", [
        "developer@example.com",
        "john.doe@company.com",
        "dependabot[bot]@users.noreply.github.com",
    ])
    def test_ignores_human_and_other_bot_emails(self, email):
        for pattern, _ in BOT_AUTHOR_PATTERNS:
            assert not re.search(pattern, email, re.IGNORECASE), \
                f"False positive on: {email}"


class TestBranchPatterns:
    @pytest.mark.parametrize("branch", [
        "copilot/fix-something",
        "claude/refactor",
        "ai-generated-fix",
        "ai/feature",
        "cursor-fix",
        "aider-refactor",
        "gemini-feature",
        "devin-implement",
        "sweep-cleanup",
    ])
    def test_matches_ai_branch_names(self, branch):
        matched = any(
            re.search(p, branch, re.IGNORECASE)
            for p in BRANCH_PATTERNS
        )
        assert matched, f"No pattern matched: {branch}"

    @pytest.mark.parametrize("branch", [
        "feature/user-auth",
        "fix/login-bug",
        "main",
        "release-2.14",
        "hotfix/critical-patch",
    ])
    def test_ignores_normal_branch_names(self, branch):
        for pattern in BRANCH_PATTERNS:
            assert not re.search(pattern, branch, re.IGNORECASE), \
                f"False positive on: {branch}"


class TestCommentPatterns:
    @pytest.mark.parametrize("comment", [
        "# generated by copilot",
        "// generated with Claude",
        "/* generated using AI */",
        "# copilot-generated",
        "# copilot generated",
        "// claude wrote this",
        "# gpt4 generated this",
        "# @generated by copilot",
    ])
    def test_matches_ai_comments(self, comment):
        matched = any(
            re.search(p, comment, re.IGNORECASE)
            for p, _ in COMMENT_PATTERNS
        )
        assert matched, f"No pattern matched: {comment}"

    @pytest.mark.parametrize("comment", [
        "# Auto-generated by protobuf compiler",
        "// This function handles authentication",
        "# TODO: refactor this later",
        "/* Copyright 2024 */",
    ])
    def test_ignores_normal_comments(self, comment):
        for pattern, _ in COMMENT_PATTERNS:
            assert not re.search(pattern, comment, re.IGNORECASE), \
                f"False positive on: {comment}"
