"""Tests for source tree and file comment scanning."""

import pytest

from ai_trace_scan.source_scan import (
    _get_lexer,
    _is_plain_text,
    _scan_file,
    scan_config_files,
    scan_source_tree,
    scan_workflows,
)


class TestIsPlainText:
    @pytest.mark.parametrize(
        "name",
        [
            "README.md",
            "notes.txt",
            "doc.rst",
            "guide.adoc",
            "Makefile",
            "Dockerfile",
            "Jenkinsfile",
        ],
    )
    def test_recognizes_text_files(self, name, tmp_path):
        f = tmp_path / name
        assert _is_plain_text(f) is True

    @pytest.mark.parametrize(
        "name",
        [
            "image.png",
            "binary.exe",
            "data.bin",
            "archive.tar.gz",
        ],
    )
    def test_rejects_non_text_files(self, name, tmp_path):
        f = tmp_path / name
        assert _is_plain_text(f) is False


class TestGetLexer:
    def test_returns_lexer_for_python(self, tmp_path):
        f = tmp_path / "test.py"
        assert _get_lexer(f) is not None

    def test_returns_lexer_for_javascript(self, tmp_path):
        f = tmp_path / "test.js"
        assert _get_lexer(f) is not None

    def test_returns_none_for_unknown(self, tmp_path):
        f = tmp_path / "test.xyz123"
        assert _get_lexer(f) is None


class TestScanFile:
    def test_detects_ai_comment_in_python(self, tmp_path):
        f = tmp_path / "example.py"
        f.write_text("# generated by copilot\nx = 1\n")
        findings = _scan_file(f, tmp_path)
        assert len(findings) == 1
        assert findings[0].category == "source-comment"
        assert "AI generation attribution" in findings[0].message

    def test_ignores_string_literal_in_python(self, tmp_path):
        f = tmp_path / "example.py"
        f.write_text('msg = "generated by copilot"\n')
        findings = _scan_file(f, tmp_path)
        assert len(findings) == 0

    def test_detects_ai_comment_in_javascript(self, tmp_path):
        f = tmp_path / "example.js"
        f.write_text("// generated with Claude\nconst x = 1;\n")
        findings = _scan_file(f, tmp_path)
        assert len(findings) == 1

    def test_ignores_string_literal_in_javascript(self, tmp_path):
        f = tmp_path / "example.js"
        f.write_text('const msg = "generated with Claude";\n')
        findings = _scan_file(f, tmp_path)
        assert len(findings) == 0

    def test_scans_plain_text_file(self, tmp_path):
        f = tmp_path / "notes.txt"
        f.write_text("This was generated by copilot.\n")
        findings = _scan_file(f, tmp_path)
        assert len(findings) >= 1

    def test_no_findings_in_clean_file(self, tmp_path):
        f = tmp_path / "clean.py"
        f.write_text("# Standard utility functions\ndef add(a, b):\n    return a + b\n")
        findings = _scan_file(f, tmp_path)
        assert len(findings) == 0

    def test_detects_hash_comment_in_shell(self, tmp_path):
        f = tmp_path / "script.sh"
        f.write_text("#!/bin/bash\n# generated by copilot\necho hello\n")
        findings = _scan_file(f, tmp_path)
        assert len(findings) == 1


class TestScanConfigFiles:
    def test_detects_agents_md(self, tmp_path):
        (tmp_path / "AGENTS.md").write_text("config")
        findings = scan_config_files(tmp_path, lambda _: False)
        assert any(f.location == "AGENTS.md" for f in findings)
        assert any(f.severity == "high" for f in findings)

    def test_detects_claude_md(self, tmp_path):
        (tmp_path / "CLAUDE.md").write_text("config")
        findings = scan_config_files(tmp_path, lambda _: False)
        assert any(f.location == "CLAUDE.md" for f in findings)

    def test_detects_cursorrules(self, tmp_path):
        (tmp_path / ".cursorrules").write_text("rules")
        findings = scan_config_files(tmp_path, lambda _: False)
        assert any(f.location == ".cursorrules" for f in findings)
        assert any(f.severity == "medium" for f in findings)

    def test_detects_github_copilot_instructions(self, tmp_path):
        gh = tmp_path / ".github"
        gh.mkdir()
        (gh / "copilot-instructions.md").write_text("instructions")
        findings = scan_config_files(tmp_path, lambda _: False)
        assert any("copilot-instructions" in f.location for f in findings)

    def test_no_findings_when_clean(self, tmp_path):
        (tmp_path / "README.md").write_text("clean project")
        findings = scan_config_files(tmp_path, lambda _: False)
        assert len(findings) == 0

    def test_respects_exclude(self, tmp_path):
        (tmp_path / "AGENTS.md").write_text("config")
        (tmp_path / "CLAUDE.md").write_text("config")

        def exclude_fn(s):
            return "AGENTS" in s

        findings = scan_config_files(tmp_path, exclude_fn)
        locations = [f.location for f in findings]
        assert "AGENTS.md" not in locations
        assert "CLAUDE.md" in locations


class TestScanSourceTree:
    def test_finds_ai_comment_in_tree(self, tmp_path):
        sub = tmp_path / "src"
        sub.mkdir()
        (sub / "app.py").write_text("# generated by copilot\nx = 1\n")
        findings = scan_source_tree(tmp_path, lambda _: False)
        assert len(findings) == 1
        assert "src/app.py" in findings[0].location

    def test_skips_node_modules(self, tmp_path):
        nm = tmp_path / "node_modules" / "pkg"
        nm.mkdir(parents=True)
        (nm / "index.js").write_text("// generated by copilot\n")
        findings = scan_source_tree(tmp_path, lambda _: False)
        assert len(findings) == 0

    def test_respects_gitignore(self, tmp_path):
        (tmp_path / ".gitignore").write_text("dist/\n")
        dist = tmp_path / "dist"
        dist.mkdir()
        (dist / "bundle.js").write_text("// generated by copilot\n")
        findings = scan_source_tree(tmp_path, lambda _: False)
        assert len(findings) == 0

    def test_respects_exclude_fn(self, tmp_path):
        (tmp_path / "keep.py").write_text("# generated by copilot\n")
        (tmp_path / "skip.py").write_text("# generated by copilot\n")

        def exclude_fn(s):
            return "skip" in s

        findings = scan_source_tree(tmp_path, exclude_fn)
        assert len(findings) == 1
        assert "keep.py" in findings[0].location


class TestScanWorkflows:
    @staticmethod
    def _make_workflow(tmp_path, filename: str, content: str):
        wf_dir = tmp_path / ".github" / "workflows"
        wf_dir.mkdir(parents=True, exist_ok=True)
        wf = wf_dir / filename
        wf.write_text(content)
        return wf

    def test_detects_copilot_action(self, tmp_path):
        self._make_workflow(
            tmp_path,
            "ci.yml",
            "jobs:\n  build:\n    steps:\n      - uses: github/copilot-action@v1\n",
        )
        findings = scan_workflows(tmp_path, lambda _: False)
        assert len(findings) >= 1
        assert findings[0].category == "workflow"
        assert findings[0].severity == "medium"
        assert "AI tool action in workflow" in findings[0].message
        assert ".github/workflows/ci.yml:" in findings[0].location

    def test_detects_openai_api_key(self, tmp_path):
        self._make_workflow(
            tmp_path,
            "deploy.yaml",
            "env:\n  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}\n",
        )
        findings = scan_workflows(tmp_path, lambda _: False)
        assert len(findings) >= 1
        assert any("API key reference" in f.message for f in findings)

    def test_ignores_normal_workflow(self, tmp_path):
        self._make_workflow(
            tmp_path,
            "test.yml",
            "name: CI\non: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm test\n",
        )
        findings = scan_workflows(tmp_path, lambda _: False)
        assert len(findings) == 0

    def test_respects_exclude_fn(self, tmp_path):
        self._make_workflow(
            tmp_path,
            "ai.yml",
            "steps:\n  - uses: github/copilot-action@v1\n",
        )
        findings = scan_workflows(tmp_path, lambda s: "ai.yml" in s)
        assert len(findings) == 0

    def test_no_workflows_dir(self, tmp_path):
        findings = scan_workflows(tmp_path, lambda _: False)
        assert len(findings) == 0

    def test_detects_ai_code_review_action(self, tmp_path):
        self._make_workflow(
            tmp_path,
            "review.yml",
            "steps:\n  - uses: coderabbitai/coderabbit@v1\n",
        )
        findings = scan_workflows(tmp_path, lambda _: False)
        assert len(findings) >= 1
        assert any("AI code review action" in f.message for f in findings)

    def test_detects_ai_sdk_install(self, tmp_path):
        self._make_workflow(
            tmp_path,
            "setup.yml",
            "steps:\n  - run: pip install openai\n",
        )
        findings = scan_workflows(tmp_path, lambda _: False)
        assert len(findings) >= 1
        assert any("AI SDK installation" in f.message for f in findings)


class TestProsePatternScanning:
    def test_detects_written_by_claude_in_markdown(self, tmp_path):
        f = tmp_path / "README.md"
        f.write_text("# My Project\n\nThis was written by Claude.\n")
        findings = _scan_file(f, tmp_path)
        prose_findings = [f for f in findings if f.category == "prose-content"]
        assert len(prose_findings) >= 1
        assert any("AI authorship attribution" in f.message for f in prose_findings)

    def test_detects_document_generated_using_gpt_in_markdown(self, tmp_path):
        f = tmp_path / "README.md"
        f.write_text("# Guide\n\nThis document was generated using GPT-4.\n")
        findings = _scan_file(f, tmp_path)
        prose_findings = [f for f in findings if f.category == "prose-content"]
        assert len(prose_findings) >= 1
        assert any("AI-generated document attribution" in f.message for f in prose_findings)

    def test_python_code_not_in_comment_not_detected(self, tmp_path):
        f = tmp_path / "example.py"
        f.write_text('status = "written by Claude"\nprint(status)\n')
        findings = _scan_file(f, tmp_path)
        assert len(findings) == 0

    def test_detects_prose_patterns_in_txt_file(self, tmp_path):
        f = tmp_path / "notes.txt"
        f.write_text("This guide was powered by Copilot.\n")
        findings = _scan_file(f, tmp_path)
        prose_findings = [f for f in findings if f.category == "prose-content"]
        assert len(prose_findings) >= 1
        assert any("AI tool attribution" in f.message for f in prose_findings)
